// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsiam.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class UserOutput {
    /**
     * @return The ARN assigned by AWS for this user.
     * 
     */
    private final @Nullable String arn;
    /**
     * @return The encrypted password, base64 encoded.
     * 
     */
    private final @Nullable String loginProfileEncryptedPassword;
    /**
     * @return The fingerprint of the PGP key used to encrypt the password.
     * 
     */
    private final @Nullable String loginProfileKeyFingerprint;
    /**
     * @return The user password.
     * 
     */
    private final @Nullable String loginProfilePassword;
    /**
     * @return The user&#39;s name.
     * 
     */
    private final @Nullable String name;
    /**
     * @return The unique identifier for the SSH public key.
     * 
     */
    private final @Nullable String sshKeyFingerprint;
    /**
     * @return The unique identifier for the SSH public key
     * 
     */
    private final @Nullable String sshKeySshPublicKeyId;
    /**
     * @return The unique ID assigned by AWS.
     * 
     */
    private final @Nullable String uniqueId;

    @CustomType.Constructor
    private UserOutput(
        @CustomType.Parameter("arn") @Nullable String arn,
        @CustomType.Parameter("loginProfileEncryptedPassword") @Nullable String loginProfileEncryptedPassword,
        @CustomType.Parameter("loginProfileKeyFingerprint") @Nullable String loginProfileKeyFingerprint,
        @CustomType.Parameter("loginProfilePassword") @Nullable String loginProfilePassword,
        @CustomType.Parameter("name") @Nullable String name,
        @CustomType.Parameter("sshKeyFingerprint") @Nullable String sshKeyFingerprint,
        @CustomType.Parameter("sshKeySshPublicKeyId") @Nullable String sshKeySshPublicKeyId,
        @CustomType.Parameter("uniqueId") @Nullable String uniqueId) {
        this.arn = arn;
        this.loginProfileEncryptedPassword = loginProfileEncryptedPassword;
        this.loginProfileKeyFingerprint = loginProfileKeyFingerprint;
        this.loginProfilePassword = loginProfilePassword;
        this.name = name;
        this.sshKeyFingerprint = sshKeyFingerprint;
        this.sshKeySshPublicKeyId = sshKeySshPublicKeyId;
        this.uniqueId = uniqueId;
    }

    /**
     * @return The ARN assigned by AWS for this user.
     * 
     */
    public Optional<String> arn() {
        return Optional.ofNullable(this.arn);
    }
    /**
     * @return The encrypted password, base64 encoded.
     * 
     */
    public Optional<String> loginProfileEncryptedPassword() {
        return Optional.ofNullable(this.loginProfileEncryptedPassword);
    }
    /**
     * @return The fingerprint of the PGP key used to encrypt the password.
     * 
     */
    public Optional<String> loginProfileKeyFingerprint() {
        return Optional.ofNullable(this.loginProfileKeyFingerprint);
    }
    /**
     * @return The user password.
     * 
     */
    public Optional<String> loginProfilePassword() {
        return Optional.ofNullable(this.loginProfilePassword);
    }
    /**
     * @return The user&#39;s name.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return The unique identifier for the SSH public key.
     * 
     */
    public Optional<String> sshKeyFingerprint() {
        return Optional.ofNullable(this.sshKeyFingerprint);
    }
    /**
     * @return The unique identifier for the SSH public key
     * 
     */
    public Optional<String> sshKeySshPublicKeyId() {
        return Optional.ofNullable(this.sshKeySshPublicKeyId);
    }
    /**
     * @return The unique ID assigned by AWS.
     * 
     */
    public Optional<String> uniqueId() {
        return Optional.ofNullable(this.uniqueId);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(UserOutput defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String arn;
        private @Nullable String loginProfileEncryptedPassword;
        private @Nullable String loginProfileKeyFingerprint;
        private @Nullable String loginProfilePassword;
        private @Nullable String name;
        private @Nullable String sshKeyFingerprint;
        private @Nullable String sshKeySshPublicKeyId;
        private @Nullable String uniqueId;

        public Builder() {
    	      // Empty
        }

        public Builder(UserOutput defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.arn = defaults.arn;
    	      this.loginProfileEncryptedPassword = defaults.loginProfileEncryptedPassword;
    	      this.loginProfileKeyFingerprint = defaults.loginProfileKeyFingerprint;
    	      this.loginProfilePassword = defaults.loginProfilePassword;
    	      this.name = defaults.name;
    	      this.sshKeyFingerprint = defaults.sshKeyFingerprint;
    	      this.sshKeySshPublicKeyId = defaults.sshKeySshPublicKeyId;
    	      this.uniqueId = defaults.uniqueId;
        }

        public Builder arn(@Nullable String arn) {
            this.arn = arn;
            return this;
        }
        public Builder loginProfileEncryptedPassword(@Nullable String loginProfileEncryptedPassword) {
            this.loginProfileEncryptedPassword = loginProfileEncryptedPassword;
            return this;
        }
        public Builder loginProfileKeyFingerprint(@Nullable String loginProfileKeyFingerprint) {
            this.loginProfileKeyFingerprint = loginProfileKeyFingerprint;
            return this;
        }
        public Builder loginProfilePassword(@Nullable String loginProfilePassword) {
            this.loginProfilePassword = loginProfilePassword;
            return this;
        }
        public Builder name(@Nullable String name) {
            this.name = name;
            return this;
        }
        public Builder sshKeyFingerprint(@Nullable String sshKeyFingerprint) {
            this.sshKeyFingerprint = sshKeyFingerprint;
            return this;
        }
        public Builder sshKeySshPublicKeyId(@Nullable String sshKeySshPublicKeyId) {
            this.sshKeySshPublicKeyId = sshKeySshPublicKeyId;
            return this;
        }
        public Builder uniqueId(@Nullable String uniqueId) {
            this.uniqueId = uniqueId;
            return this;
        }        public UserOutput build() {
            return new UserOutput(arn, loginProfileEncryptedPassword, loginProfileKeyFingerprint, loginProfilePassword, name, sshKeyFingerprint, sshKeySshPublicKeyId, uniqueId);
        }
    }
}
