// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsIam
{
    [AwsIamResourceType("aws-iam:index:AssumableRoleWithSAML")]
    public partial class AssumableRoleWithSAML : Pulumi.ComponentResource
    {
        /// <summary>
        /// ARN of IAM role.
        /// </summary>
        [Output("roleArn")]
        public Output<string> RoleArn { get; private set; } = null!;

        /// <summary>
        /// Name of IAM role.
        /// </summary>
        [Output("roleName")]
        public Output<string> RoleName { get; private set; } = null!;

        /// <summary>
        /// Path of IAM role.
        /// </summary>
        [Output("rolePath")]
        public Output<string> RolePath { get; private set; } = null!;

        /// <summary>
        /// Unique ID of IAM role.
        /// </summary>
        [Output("roleUniqueId")]
        public Output<string> RoleUniqueId { get; private set; } = null!;


        /// <summary>
        /// Create a AssumableRoleWithSAML resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AssumableRoleWithSAML(string name, AssumableRoleWithSAMLArgs? args = null, ComponentResourceOptions? options = null)
            : base("aws-iam:index:AssumableRoleWithSAML", name, args ?? new AssumableRoleWithSAMLArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class AssumableRoleWithSAMLArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// AWS SAML Endpoint.
        /// </summary>
        [Input("awsSamlEndpoint")]
        public Input<string>? AwsSamlEndpoint { get; set; }

        /// <summary>
        /// Whether policies should be detached from this role when destroying.
        /// </summary>
        [Input("forceDetachPolicies")]
        public Input<bool>? ForceDetachPolicies { get; set; }

        /// <summary>
        /// Maximum CLI/API session duration in seconds between 3600 and 43200.
        /// </summary>
        [Input("maxSessionDuration")]
        public Input<int>? MaxSessionDuration { get; set; }

        [Input("providerIds")]
        private InputList<string>? _providerIds;

        /// <summary>
        /// List of SAML Provider IDs.
        /// </summary>
        public InputList<string> ProviderIds
        {
            get => _providerIds ?? (_providerIds = new InputList<string>());
            set => _providerIds = value;
        }

        [Input("role")]
        public Input<Inputs.RoleArgs>? Role { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// A map of tags to add.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        public AssumableRoleWithSAMLArgs()
        {
            AwsSamlEndpoint = "https://signin.aws.amazon.com/saml";
            ForceDetachPolicies = false;
            MaxSessionDuration = 3600;
        }
    }
}
