// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsIam
{
    [AwsIamResourceType("aws-iam:index:AssumableRoles")]
    public partial class AssumableRoles : Pulumi.ComponentResource
    {
        [Output("admin")]
        public Output<ImmutableDictionary<string, string>> Admin { get; private set; } = null!;

        [Output("poweruser")]
        public Output<ImmutableDictionary<string, string>?> Poweruser { get; private set; } = null!;

        [Output("readonly")]
        public Output<ImmutableDictionary<string, string>?> Readonly { get; private set; } = null!;


        /// <summary>
        /// Create a AssumableRoles resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AssumableRoles(string name, AssumableRolesArgs args, ComponentResourceOptions? options = null)
            : base("aws-iam:index:AssumableRoles", name, args ?? new AssumableRolesArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class AssumableRolesArgs : Pulumi.ResourceArgs
    {
        [Input("admin", required: true)]
        public Input<Inputs.AdminRoleWithMFAArgs> Admin { get; set; } = null!;

        /// <summary>
        /// Whether policies should be detached from this role when destroying.
        /// </summary>
        [Input("forceDetachPolicies")]
        public Input<bool>? ForceDetachPolicies { get; set; }

        /// <summary>
        /// Maximum CLI/API session duration in seconds between 3600 and 43200.
        /// </summary>
        [Input("maxSessionDuration")]
        public Input<int>? MaxSessionDuration { get; set; }

        /// <summary>
        /// Max age of valid MFA (in seconds) for roles which require MFA.
        /// </summary>
        [Input("mfaAge")]
        public Input<int>? MfaAge { get; set; }

        [Input("poweruser")]
        public Input<Inputs.PoweruserRoleWithMFAArgs>? Poweruser { get; set; }

        [Input("readonly")]
        public Input<Inputs.ReadonlyRoleWithMFAArgs>? Readonly { get; set; }

        [Input("trustedRoleArns")]
        private InputList<string>? _trustedRoleArns;

        /// <summary>
        /// ARNs of AWS entities who can assume these roles.
        /// </summary>
        public InputList<string> TrustedRoleArns
        {
            get => _trustedRoleArns ?? (_trustedRoleArns = new InputList<string>());
            set => _trustedRoleArns = value;
        }

        [Input("trustedRoleServices")]
        private InputList<string>? _trustedRoleServices;

        /// <summary>
        /// AWS Services that can assume these roles.
        /// </summary>
        public InputList<string> TrustedRoleServices
        {
            get => _trustedRoleServices ?? (_trustedRoleServices = new InputList<string>());
            set => _trustedRoleServices = value;
        }

        public AssumableRolesArgs()
        {
            ForceDetachPolicies = false;
            MaxSessionDuration = 3600;
            MfaAge = 86400;
        }
    }
}
