// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsIam.Outputs
{

    /// <summary>
    /// The IAM access key.
    /// </summary>
    [OutputType]
    public sealed class AccessKeyOutput
    {
        /// <summary>
        /// The encrypted secret, base64 encoded.
        /// </summary>
        public readonly string? EncryptedSecret;
        /// <summary>
        /// The access key ID.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The fingerprint of the PGP key used to encrypt the secret.
        /// </summary>
        public readonly string? KeyFingerprint;
        /// <summary>
        /// The access key secret.
        /// </summary>
        public readonly string? Secret;
        /// <summary>
        /// The secret access key converted into an SES SMTP password by applying AWS's Sigv4 conversion algorithm.
        /// </summary>
        public readonly string? SesSmtpPasswordV4;
        /// <summary>
        /// Active or Inactive. Keys are initially active, but can be made inactive by other means.
        /// </summary>
        public readonly string? Status;

        [OutputConstructor]
        private AccessKeyOutput(
            string? encryptedSecret,

            string? id,

            string? keyFingerprint,

            string? secret,

            string? sesSmtpPasswordV4,

            string? status)
        {
            EncryptedSecret = encryptedSecret;
            Id = id;
            KeyFingerprint = keyFingerprint;
            Secret = secret;
            SesSmtpPasswordV4 = sesSmtpPasswordV4;
            Status = status;
        }
    }
}
