// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsiam;

import com.pulumi.awsiam.AssumableRolesArgs;
import com.pulumi.awsiam.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="aws-iam:index:AssumableRoles")
public class AssumableRoles extends com.pulumi.resources.ComponentResource {
    @Export(name="admin", type=Map.class, parameters={String.class, String.class})
    private Output<Map<String,String>> admin;

    public Output<Map<String,String>> admin() {
        return this.admin;
    }
    @Export(name="poweruser", type=Map.class, parameters={String.class, String.class})
    private Output</* @Nullable */ Map<String,String>> poweruser;

    public Output<Optional<Map<String,String>>> poweruser() {
        return Codegen.optional(this.poweruser);
    }
    @Export(name="readonly", type=Map.class, parameters={String.class, String.class})
    private Output</* @Nullable */ Map<String,String>> readonly;

    public Output<Optional<Map<String,String>>> readonly() {
        return Codegen.optional(this.readonly);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public AssumableRoles(String name) {
        this(name, AssumableRolesArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public AssumableRoles(String name, AssumableRolesArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public AssumableRoles(String name, AssumableRolesArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        super("aws-iam:index:AssumableRoles", name, args == null ? AssumableRolesArgs.Empty : args, makeResourceOptions(options, Codegen.empty()), true);
    }

    private static com.pulumi.resources.ComponentResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.ComponentResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.ComponentResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.ComponentResourceOptions.merge(defaultOptions, options, id);
    }

}
