// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsiam;

import com.pulumi.awsiam.inputs.RoleArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class EKSRoleArgs extends com.pulumi.resources.ResourceArgs {

    public static final EKSRoleArgs Empty = new EKSRoleArgs();

    /**
     * EKS cluster and k8s ServiceAccount pairs. Each EKS cluster can have multiple k8s ServiceAccount. See README for details
     * 
     */
    @Import(name="clusterServiceAccounts")
    private @Nullable Output<Map<String,List<String>>> clusterServiceAccounts;

    /**
     * @return EKS cluster and k8s ServiceAccount pairs. Each EKS cluster can have multiple k8s ServiceAccount. See README for details
     * 
     */
    public Optional<Output<Map<String,List<String>>>> clusterServiceAccounts() {
        return Optional.ofNullable(this.clusterServiceAccounts);
    }

    /**
     * Whether policies should be detached from this role when destroying.
     * 
     */
    @Import(name="forceDetachPolicies")
    private @Nullable Output<Boolean> forceDetachPolicies;

    /**
     * @return Whether policies should be detached from this role when destroying.
     * 
     */
    public Optional<Output<Boolean>> forceDetachPolicies() {
        return Optional.ofNullable(this.forceDetachPolicies);
    }

    /**
     * Maximum CLI/API session duration in seconds between 3600 and 43200.
     * 
     */
    @Import(name="maxSessionDuration")
    private @Nullable Output<Integer> maxSessionDuration;

    /**
     * @return Maximum CLI/API session duration in seconds between 3600 and 43200.
     * 
     */
    public Optional<Output<Integer>> maxSessionDuration() {
        return Optional.ofNullable(this.maxSessionDuration);
    }

    /**
     * OIDC provider URL and k8s ServiceAccount pairs. If the assume role policy requires a mix of EKS clusters and other OIDC providers then this can be used
     * 
     */
    @Import(name="providerUrlSaPairs")
    private @Nullable Output<Map<String,List<String>>> providerUrlSaPairs;

    /**
     * @return OIDC provider URL and k8s ServiceAccount pairs. If the assume role policy requires a mix of EKS clusters and other OIDC providers then this can be used
     * 
     */
    public Optional<Output<Map<String,List<String>>>> providerUrlSaPairs() {
        return Optional.ofNullable(this.providerUrlSaPairs);
    }

    @Import(name="role")
    private @Nullable Output<RoleArgs> role;

    public Optional<Output<RoleArgs>> role() {
        return Optional.ofNullable(this.role);
    }

    /**
     * ARNs of any policies to attach to the IAM role.
     * 
     */
    @Import(name="rolePolicyArns")
    private @Nullable Output<List<String>> rolePolicyArns;

    /**
     * @return ARNs of any policies to attach to the IAM role.
     * 
     */
    public Optional<Output<List<String>>> rolePolicyArns() {
        return Optional.ofNullable(this.rolePolicyArns);
    }

    /**
     * A map of tags to add.
     * 
     */
    @Import(name="tags")
    private @Nullable Output<Map<String,String>> tags;

    /**
     * @return A map of tags to add.
     * 
     */
    public Optional<Output<Map<String,String>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    private EKSRoleArgs() {}

    private EKSRoleArgs(EKSRoleArgs $) {
        this.clusterServiceAccounts = $.clusterServiceAccounts;
        this.forceDetachPolicies = $.forceDetachPolicies;
        this.maxSessionDuration = $.maxSessionDuration;
        this.providerUrlSaPairs = $.providerUrlSaPairs;
        this.role = $.role;
        this.rolePolicyArns = $.rolePolicyArns;
        this.tags = $.tags;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EKSRoleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EKSRoleArgs $;

        public Builder() {
            $ = new EKSRoleArgs();
        }

        public Builder(EKSRoleArgs defaults) {
            $ = new EKSRoleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param clusterServiceAccounts EKS cluster and k8s ServiceAccount pairs. Each EKS cluster can have multiple k8s ServiceAccount. See README for details
         * 
         * @return builder
         * 
         */
        public Builder clusterServiceAccounts(@Nullable Output<Map<String,List<String>>> clusterServiceAccounts) {
            $.clusterServiceAccounts = clusterServiceAccounts;
            return this;
        }

        /**
         * @param clusterServiceAccounts EKS cluster and k8s ServiceAccount pairs. Each EKS cluster can have multiple k8s ServiceAccount. See README for details
         * 
         * @return builder
         * 
         */
        public Builder clusterServiceAccounts(Map<String,List<String>> clusterServiceAccounts) {
            return clusterServiceAccounts(Output.of(clusterServiceAccounts));
        }

        /**
         * @param forceDetachPolicies Whether policies should be detached from this role when destroying.
         * 
         * @return builder
         * 
         */
        public Builder forceDetachPolicies(@Nullable Output<Boolean> forceDetachPolicies) {
            $.forceDetachPolicies = forceDetachPolicies;
            return this;
        }

        /**
         * @param forceDetachPolicies Whether policies should be detached from this role when destroying.
         * 
         * @return builder
         * 
         */
        public Builder forceDetachPolicies(Boolean forceDetachPolicies) {
            return forceDetachPolicies(Output.of(forceDetachPolicies));
        }

        /**
         * @param maxSessionDuration Maximum CLI/API session duration in seconds between 3600 and 43200.
         * 
         * @return builder
         * 
         */
        public Builder maxSessionDuration(@Nullable Output<Integer> maxSessionDuration) {
            $.maxSessionDuration = maxSessionDuration;
            return this;
        }

        /**
         * @param maxSessionDuration Maximum CLI/API session duration in seconds between 3600 and 43200.
         * 
         * @return builder
         * 
         */
        public Builder maxSessionDuration(Integer maxSessionDuration) {
            return maxSessionDuration(Output.of(maxSessionDuration));
        }

        /**
         * @param providerUrlSaPairs OIDC provider URL and k8s ServiceAccount pairs. If the assume role policy requires a mix of EKS clusters and other OIDC providers then this can be used
         * 
         * @return builder
         * 
         */
        public Builder providerUrlSaPairs(@Nullable Output<Map<String,List<String>>> providerUrlSaPairs) {
            $.providerUrlSaPairs = providerUrlSaPairs;
            return this;
        }

        /**
         * @param providerUrlSaPairs OIDC provider URL and k8s ServiceAccount pairs. If the assume role policy requires a mix of EKS clusters and other OIDC providers then this can be used
         * 
         * @return builder
         * 
         */
        public Builder providerUrlSaPairs(Map<String,List<String>> providerUrlSaPairs) {
            return providerUrlSaPairs(Output.of(providerUrlSaPairs));
        }

        public Builder role(@Nullable Output<RoleArgs> role) {
            $.role = role;
            return this;
        }

        public Builder role(RoleArgs role) {
            return role(Output.of(role));
        }

        /**
         * @param rolePolicyArns ARNs of any policies to attach to the IAM role.
         * 
         * @return builder
         * 
         */
        public Builder rolePolicyArns(@Nullable Output<List<String>> rolePolicyArns) {
            $.rolePolicyArns = rolePolicyArns;
            return this;
        }

        /**
         * @param rolePolicyArns ARNs of any policies to attach to the IAM role.
         * 
         * @return builder
         * 
         */
        public Builder rolePolicyArns(List<String> rolePolicyArns) {
            return rolePolicyArns(Output.of(rolePolicyArns));
        }

        /**
         * @param rolePolicyArns ARNs of any policies to attach to the IAM role.
         * 
         * @return builder
         * 
         */
        public Builder rolePolicyArns(String... rolePolicyArns) {
            return rolePolicyArns(List.of(rolePolicyArns));
        }

        /**
         * @param tags A map of tags to add.
         * 
         * @return builder
         * 
         */
        public Builder tags(@Nullable Output<Map<String,String>> tags) {
            $.tags = tags;
            return this;
        }

        /**
         * @param tags A map of tags to add.
         * 
         * @return builder
         * 
         */
        public Builder tags(Map<String,String> tags) {
            return tags(Output.of(tags));
        }

        public EKSRoleArgs build() {
            $.forceDetachPolicies = Codegen.booleanProp("forceDetachPolicies").output().arg($.forceDetachPolicies).def(false).getNullable();
            $.maxSessionDuration = Codegen.integerProp("maxSessionDuration").output().arg($.maxSessionDuration).def(3600).getNullable();
            return $;
        }
    }

}
