// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsiam.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * The Load Balancer policy.
 * 
 */
public final class EKSLoadBalancerPolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final EKSLoadBalancerPolicyArgs Empty = new EKSLoadBalancerPolicyArgs();

    /**
     * Determines whether to attach the Load Balancer Controller policy to the role.
     * 
     */
    @Import(name="controller")
    private @Nullable Output<Boolean> controller;

    /**
     * @return Determines whether to attach the Load Balancer Controller policy to the role.
     * 
     */
    public Optional<Output<Boolean>> controller() {
        return Optional.ofNullable(this.controller);
    }

    /**
     * Determines whether to attach the Load Balancer Controller policy for the TargetGroupBinding only.
     * 
     */
    @Import(name="targetGroupBindingOnly")
    private @Nullable Output<Boolean> targetGroupBindingOnly;

    /**
     * @return Determines whether to attach the Load Balancer Controller policy for the TargetGroupBinding only.
     * 
     */
    public Optional<Output<Boolean>> targetGroupBindingOnly() {
        return Optional.ofNullable(this.targetGroupBindingOnly);
    }

    private EKSLoadBalancerPolicyArgs() {}

    private EKSLoadBalancerPolicyArgs(EKSLoadBalancerPolicyArgs $) {
        this.controller = $.controller;
        this.targetGroupBindingOnly = $.targetGroupBindingOnly;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EKSLoadBalancerPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EKSLoadBalancerPolicyArgs $;

        public Builder() {
            $ = new EKSLoadBalancerPolicyArgs();
        }

        public Builder(EKSLoadBalancerPolicyArgs defaults) {
            $ = new EKSLoadBalancerPolicyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param controller Determines whether to attach the Load Balancer Controller policy to the role.
         * 
         * @return builder
         * 
         */
        public Builder controller(@Nullable Output<Boolean> controller) {
            $.controller = controller;
            return this;
        }

        /**
         * @param controller Determines whether to attach the Load Balancer Controller policy to the role.
         * 
         * @return builder
         * 
         */
        public Builder controller(Boolean controller) {
            return controller(Output.of(controller));
        }

        /**
         * @param targetGroupBindingOnly Determines whether to attach the Load Balancer Controller policy for the TargetGroupBinding only.
         * 
         * @return builder
         * 
         */
        public Builder targetGroupBindingOnly(@Nullable Output<Boolean> targetGroupBindingOnly) {
            $.targetGroupBindingOnly = targetGroupBindingOnly;
            return this;
        }

        /**
         * @param targetGroupBindingOnly Determines whether to attach the Load Balancer Controller policy for the TargetGroupBinding only.
         * 
         * @return builder
         * 
         */
        public Builder targetGroupBindingOnly(Boolean targetGroupBindingOnly) {
            return targetGroupBindingOnly(Output.of(targetGroupBindingOnly));
        }

        public EKSLoadBalancerPolicyArgs build() {
            return $;
        }
    }

}
