// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awsiam.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * The Velero IAM policy to the role.
 * 
 */
public final class EKSVeleroPolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final EKSVeleroPolicyArgs Empty = new EKSVeleroPolicyArgs();

    /**
     * Determines whether to attach the Velero IAM policy to the role.
     * 
     */
    @Import(name="attach", required=true)
    private Output<Boolean> attach;

    /**
     * @return Determines whether to attach the Velero IAM policy to the role.
     * 
     */
    public Output<Boolean> attach() {
        return this.attach;
    }

    /**
     * List of S3 Bucket ARNs that Velero needs access to in order to backup and restore cluster resources.
     * If not provided, a default ARN of &#34;*&#34; will be provided.
     * 
     */
    @Import(name="s3BucketArns")
    private @Nullable Output<List<String>> s3BucketArns;

    /**
     * @return List of S3 Bucket ARNs that Velero needs access to in order to backup and restore cluster resources.
     * If not provided, a default ARN of &#34;*&#34; will be provided.
     * 
     */
    public Optional<Output<List<String>>> s3BucketArns() {
        return Optional.ofNullable(this.s3BucketArns);
    }

    private EKSVeleroPolicyArgs() {}

    private EKSVeleroPolicyArgs(EKSVeleroPolicyArgs $) {
        this.attach = $.attach;
        this.s3BucketArns = $.s3BucketArns;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EKSVeleroPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EKSVeleroPolicyArgs $;

        public Builder() {
            $ = new EKSVeleroPolicyArgs();
        }

        public Builder(EKSVeleroPolicyArgs defaults) {
            $ = new EKSVeleroPolicyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param attach Determines whether to attach the Velero IAM policy to the role.
         * 
         * @return builder
         * 
         */
        public Builder attach(Output<Boolean> attach) {
            $.attach = attach;
            return this;
        }

        /**
         * @param attach Determines whether to attach the Velero IAM policy to the role.
         * 
         * @return builder
         * 
         */
        public Builder attach(Boolean attach) {
            return attach(Output.of(attach));
        }

        /**
         * @param s3BucketArns List of S3 Bucket ARNs that Velero needs access to in order to backup and restore cluster resources.
         * If not provided, a default ARN of &#34;*&#34; will be provided.
         * 
         * @return builder
         * 
         */
        public Builder s3BucketArns(@Nullable Output<List<String>> s3BucketArns) {
            $.s3BucketArns = s3BucketArns;
            return this;
        }

        /**
         * @param s3BucketArns List of S3 Bucket ARNs that Velero needs access to in order to backup and restore cluster resources.
         * If not provided, a default ARN of &#34;*&#34; will be provided.
         * 
         * @return builder
         * 
         */
        public Builder s3BucketArns(List<String> s3BucketArns) {
            return s3BucketArns(Output.of(s3BucketArns));
        }

        /**
         * @param s3BucketArns List of S3 Bucket ARNs that Velero needs access to in order to backup and restore cluster resources.
         * If not provided, a default ARN of &#34;*&#34; will be provided.
         * 
         * @return builder
         * 
         */
        public Builder s3BucketArns(String... s3BucketArns) {
            return s3BucketArns(List.of(s3BucketArns));
        }

        public EKSVeleroPolicyArgs build() {
            $.attach = Objects.requireNonNull($.attach, "expected parameter 'attach' to be non-null");
            return $;
        }
    }

}
