// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsIam.Inputs
{

    /// <summary>
    /// The Cert Manager IAM policy to attach to the role.
    /// </summary>
    public sealed class EKSCertManagerPolicyArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Determines whether to attach the Cert Manager IAM policy to the role.
        /// </summary>
        [Input("attach", required: true)]
        public Input<bool> Attach { get; set; } = null!;

        [Input("hostedZoneArns")]
        private InputList<string>? _hostedZoneArns;

        /// <summary>
        /// Route53 hosted zone ARNs to allow Cert manager to manage records. If not provided,
        /// the default ARN "arn:aws:route53:::hostedzone/*" will be applied.
        /// </summary>
        public InputList<string> HostedZoneArns
        {
            get => _hostedZoneArns ?? (_hostedZoneArns = new InputList<string>());
            set => _hostedZoneArns = value;
        }

        public EKSCertManagerPolicyArgs()
        {
        }
    }
}
