// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsIam.Inputs
{

    /// <summary>
    /// The External Secrets policy to the role.
    /// </summary>
    public sealed class EKSExternalSecretsPolicyArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Determines whether to attach the External Secrets policy to the role.
        /// </summary>
        [Input("attach", required: true)]
        public Input<bool> Attach { get; set; } = null!;

        [Input("secretsManagerArns")]
        private InputList<string>? _secretsManagerArns;

        /// <summary>
        /// List of Secrets Manager ARNs that contain secrets to mount using External Secrets. If not provided, the default ARN "arn:aws:secretsmanager:*:*:secret:*" will be applied.
        /// </summary>
        public InputList<string> SecretsManagerArns
        {
            get => _secretsManagerArns ?? (_secretsManagerArns = new InputList<string>());
            set => _secretsManagerArns = value;
        }

        [Input("ssmParameterArns")]
        private InputList<string>? _ssmParameterArns;

        /// <summary>
        /// List of Systems Manager Parameter ARNs that contain secrets to mount using External Secrets. If not provided,
        /// the default ARN "arn:aws:ssm:*:*:parameter/*" will be applied.
        /// </summary>
        public InputList<string> SsmParameterArns
        {
            get => _ssmParameterArns ?? (_ssmParameterArns = new InputList<string>());
            set => _ssmParameterArns = value;
        }

        public EKSExternalSecretsPolicyArgs()
        {
        }
    }
}
