// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsIam.Inputs
{

    /// <summary>
    /// The EFS CSI IAM policy to the role.
    /// </summary>
    public sealed class EKSEFSCSIPolicyArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Determines whether to attach the EFS CSI IAM policy to the role.
        /// </summary>
        [Input("attach", required: true)]
        public Input<bool> Attach { get; set; } = null!;

        public EKSEFSCSIPolicyArgs()
        {
        }
    }
}
