// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AwsIam.Inputs
{

    /// <summary>
    /// The Velero IAM policy to the role.
    /// </summary>
    public sealed class EKSVeleroPolicyArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Determines whether to attach the Velero IAM policy to the role.
        /// </summary>
        [Input("attach", required: true)]
        public Input<bool> Attach { get; set; } = null!;

        [Input("s3BucketArns")]
        private InputList<string>? _s3BucketArns;

        /// <summary>
        /// List of S3 Bucket ARNs that Velero needs access to in order to backup and restore cluster resources.
        /// If not provided, a default ARN of "*" will be provided.
        /// </summary>
        public InputList<string> S3BucketArns
        {
            get => _s3BucketArns ?? (_s3BucketArns = new InputList<string>());
            set => _s3BucketArns = value;
        }

        public EKSVeleroPolicyArgs()
        {
        }
    }
}
